cc_library(
    name = "budget_calculator",
    srcs = [
        "budget.cpp",
        "budget_calculator.cpp",
    ],
    hdrs = [
        "budget.h",
        "budget_calculator.h",
        "budget_repo.h",
        "date.h",
    ],
    visibility = ["//visibility:public"],
)
